blank_issues_enabled: false
contact_links:
    - name: Request a feature
      url: https://github.com/GertjanRoke/laravel-db-model/issues/new
      about: Share ideas for new features
    - name: Report a bug
      url: https://github.com/GertjanRoke/laravel-db-model/issues/new
      about: Report a reproducable bug
